# Java
# Package your Java project.
# Add steps that install, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master
      - ithc

  tags:
    include:
      - v*

pr:
  autoCancel: true
  branches:
    include:
      - master

variables:
  #  group: pipeline-env-variables
  ${{ if startsWith( variables['Build.SourceBranch'], 'refs/pull/') }}:
    environment: 'test'
    env.upper: 'TEST'
  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')) }}:
    environment: 'stg' #Use test and promoting to stg until prod is ready
    env.upper: 'STG'
  env.prom: 'prod'
  env.prom.upper: 'PROD'
  application.name: 'mi-extraction-service'
  azure.container.registry: 'ssprivate$(env).azurecr.io'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'
  azure.aks.resourcegroup: 'ss_$(env)_kubernetes_resource_group'
  azure.aks.cluster: 'ss_aks_$(env)'
  azure.prom.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.prom.upper)'
  azure.prom.aks.resourcegroup: 'ss_$(env.prom)_kubernetes_resource_group'
  azure.prom.aks.cluster: 'ss_aks_$(env.prom)'
  manual.branch.prefix: 'master'
  product: 'mi'
  vault: 'mi-vault-$(env)'
  azure.prom.acr: 'ssprivate$(env.prom)'
  helm.repo: 'ssprivate$(env)'

resources:
  repositories:
    - repository: mi-core
      type: github
      name: hmcts/mi-core-lib
      endpoint: hmcts

stages:
  - template: pipeline-steps/templates/build-deploy-stage.yaml@mi-core
    parameters:
      env: $(environment)
      applicationName: $(application.name)
      product: $(product)
      chartEnv: $(environment)
      preIntegrationTest: true
      functionalTest: true
      mutationTest: false
      helmRepo: $(helm.repo)
      envMapping:
        - key: BUILD_VERSION
          value: Build.BuildId
      promEnv: $(env.prom)
      azureVault: $(vault)
      azureSecreKeys: 'mi-staging-storage-connection-string,mi-export-storage-connection-string,gov-uk-notify-api-key,mailing-targets'
      azureKeyMapping:
        - key: STORAGE_STAGING_CONNECTION_STRING
          value: 'mi-staging-storage-connection-string'
        - key: STORAGE_EXPORT_CONNECTION_STRING
          value: 'mi-export-storage-connection-string'
        - key: GOV_UK_NOTIFY_API_KEY
          value: 'gov-uk-notify-api-key'
        - key: MAIL_TARGETS
          value: 'mailing-targets'
        - key: AZURE_CONTAINER_REGISTRY
          value: $(azure.container.registry)
