# Java
# Package your Java project.
# Add steps that install, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master
      - ithc

  tags:
    include:
      - v*

pr:
  autoCancel: true
  branches:
    include:
      - master

variables:
  #  group: pipeline-env-variables
  ${{ if not(eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
    environment: 'test'
    env.upper: 'TEST'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    environment: 'stg'
    env.upper: 'STG'
  env.prom: 'prod'
  env.prom.upper: 'PROD'
  application.name: 'mi-extraction-service'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'
  azure.aks.resourcegroup: 'ss-$(env)-00-rg'
  azure.aks.cluster: 'ss-$(env)-00-aks'
  azure.prom.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.prom.upper)'
  manual.branch.prefix: 'master'
  product: 'mi'
  vault: 'mi-vault-$(env)'
  helm.repo: 'sdshmctspublic'

resources:
  repositories:
    - repository: mi-core
      type: github
      name: hmcts/mi-core-lib
      endpoint: hmcts

stages:
  - template: pipeline-steps/templates/build-deploy-stage.yaml@mi-core
    parameters:
      env: $(environment)
      applicationName: $(application.name)
      product: $(product)
      chartEnv: $(environment)
      preIntegrationTest: true
      functionalTest: true
      mutationTest: false
      dependencyCheck: false
      helmRepo: $(helm.repo)
      agentPool: hmcts-ss-$(environment)
      promEnv: $(env.prom)
      azureVault: $(vault)
      azureSecreKeys: 'mi-staging-storage-connection-string,mi-export-storage-connection-string,gov-uk-notify-api-key,mailing-targets'
      envMapping:
      - key: ENV
        value: $(environment)
      - key: BUILD_VERSION
        value: Build.BuildId
      azureKeyMapping:
        - key: STORAGE_STAGING_CONNECTION_STRING
          value: 'mi-staging-storage-connection-string'
        - key: STORAGE_EXPORT_CONNECTION_STRING
          value: 'mi-export-storage-connection-string'
        - key: GOV_UK_NOTIFY_API_KEY
          value: 'gov-uk-notify-api-key'
        - key: MAIL_TARGETS
          value: 'mailing-targets'
        - key: SFTP_REMOTE_USER
          value: 'sftp-remote-user'
        - key: SFTP_REMOTE_PASSWORD
          value: 'sftp-remote-password'
        - key: AZURE_CONTAINER_REGISTRY
          value: $(azure.container.registry)
