mi-job:
  image: ${IMAGE_NAME}
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: 350a1a4c-d746-4c63-814c-4fee92e6e07c
    CONTAINER_WHITELIST: ccd-testcontainer-1c9640ba-d3e4-4cdb-bf04-36f00e751189
    MI_CLIENT_ID: 58ed3fc0-18be-4a6f-8ceb-14768c8e796a
    RETRIEVE_FROM_DATE: 1970-01-01
    RETRIEVE_TO_DATE: 1970-01-02
    SAS-IP-WHITELIST_RANGE_PETTY-FRANCE: 213.121.161.0-213.121.161.255
global:
  subscriptionId: "3eec5bde-7feb-4566-bfb6-805df6e10b90"
  environment: test