job:
  image: ${IMAGE_NAME}
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: 350a1a4c-d746-4c63-814c-4fee92e6e07c
    CONTAINER_WHITELIST: ^exp-testcontainer-${BUILD_VERSION}.*
    EXPORT_SOURCES_EXP_ENABLED: true
    EXPORT_SOURCES_EXP_PREFIX: ${BUILD_VERSION}
    EXPORT_SOURCES_EXP_DATEFIELD: date_updated
    EXPORT_SOURCES_EXP_TYPE: prefix
    MI_CLIENT_ID: 58ed3fc0-18be-4a6f-8ceb-14768c8e796a
    RETRIEVE_FROM_DATE: 1970-01-01
    RETRIEVE_TO_DATE: 1970-01-02
global:
  subscriptionId: "3eec5bde-7feb-4566-bfb6-805df6e10b90"
  environment: test
