mi-job:
  image: ${IMAGE_NAME}
  memoryLimits: '2048Mi'
  cpuLimits: '2000m'
  activeDeadlineSeconds: 3600
  aadIdentityName: mi-extraction-service
  keyVaultsUsepodidentity: true
  kind: Job
  labels:
    app.kubernetes.io/instance : mi-extraction-service-build-001
    app.kubernetes.io/name: mi-extraction-service-build
  environment:
    STORAGE_STAGING_NAME: mipersistent{{ .Values.global.environment }}
    STORAGE_EXPORT_NAME: miexport{{ .Values.global.environment }}
  keyVaults:
    "mi-vault":
      excludeEnvironmentSuffix: false
      resourceGroup: mi-{{ .Values.global.environment }}-rg
      secrets:
        - gov-uk-notify-api-key
        - mailing-targets

global:
  enableKeyVaults: true
  usepodidentity: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

