mi-job:
  image: ${IMAGE_NAME}
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: 482eb1b8-a656-41e6-b2e8-8351d7986b2c
    CONTAINER_WHITELIST: ^exp-testcontainer-${BUILD_VERSION}.*
    EXPORT_SOURCES_EXP_ENABLED: true
    EXPORT_SOURCES_EXP_PREFIX: ${BUILD_VERSION}
    EXPORT_SOURCES_EXP_DATEFIELD: date_updated
    EXPORT_SOURCES_EXP_TYPE: prefix
    MI_CLIENT_ID: 88d54b96-2be6-4fb5-b966-7d98111152d8
    RETRIEVE_FROM_DATE: 1970-01-01
    RETRIEVE_TO_DATE: 1970-01-02
global:
  subscriptionId: "74dacd4f-a248-45bb-a2f0-af700dc4cf68"
  environment: stg
